target("test_ini_print")
    set_kind("binary")
    add_files("test_ini_print.cpp")
    add_includedirs("../include")  
    add_cxflags("-g")
    add_rpathdirs("$ORIGIN") 
    add_ldflags("-fPIC") 
    add_deps("ini")  
    add_links("ini") 


target("test_ini_callback")
    set_kind("binary")
    add_files("test_ini_callback.c")
    add_includedirs("../include")  
    add_cxflags("-g")
    add_rpathdirs("$ORIGIN") 
    add_ldflags("-fPIC") 
    add_deps("ini")  
    add_links("ini") 